[workspace]
members = [
    "ai-ida",
    "ai-ida-common",
    "ai-ida-ebpf",
]
default-members = ["ai-ida"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["AI-IDA Developers"]

[workspace.dependencies]
anyhow = "1"
aya = "0.13.1"
aya-build = "0.2.0"
aya-log = "0.2.1"
aya-ebpf = "0.2.1"
aya-log-ebpf = "0.2.0"
cargo_metadata = "0.23"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
libc = "0.2"
log = "0.4"
tokio = { version = "1", features = ["full"] }
which = "6"

[profile.dev]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = true

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true