[package]
name = "ai-ida-ebpf"
version.workspace = true
edition.workspace = true

[dependencies]
aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }
ai-ida-common = { path = "../ai-ida-common" }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "ai-ida"
path = "src/main.rs"